### ISSUE TITLE
Speed and potential issues ?

### ISSUE THREAD

**Issue by fxfactorial** [umbracle/fastrlp#2]
How much faster is this over plain rlp encoding on average ? Is it also better in memory performance ? Are there any compatibility  issues from this rlp encoding version and what mainline ethereum uses ? 

Thank you

**Comment by ferranbt** [comment]
There is a benchmark at the bottom of the README with benchmarks with respect to Geth. https://github.com/umbracle/fastrlp#benchmark
The encoding format is the same.

**Comment by anukul** [comment]
Can we look at the source for this benchmark? cc @ferranbt
